// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnikljJd3sJB3pyjdkR0zJ0Z1vvXoI_pA',
    appId: '1:274244221752:web:591d769bae23e3e4169fcd',
    messagingSenderId: '274244221752',
    projectId: 'rememberme-860f1',
    authDomain: 'rememberme-860f1.firebaseapp.com',
    storageBucket: 'rememberme-860f1.firebasestorage.app',
    measurementId: 'G-6FBYFXFTBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxJtICS45TEs3S1DfAEcreSOBgFTS69oE',
    appId: '1:274244221752:android:8066ee861b6872a4169fcd',
    messagingSenderId: '274244221752',
    projectId: 'rememberme-860f1',
    storageBucket: 'rememberme-860f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPGOUsL5nWSJRbbkeXZtsMoMtrINPVrmY',
    appId: '1:274244221752:ios:7af04994421a8f6e169fcd',
    messagingSenderId: '274244221752',
    projectId: 'rememberme-860f1',
    storageBucket: 'rememberme-860f1.firebasestorage.app',
    iosBundleId: 'com.example.rememberme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPGOUsL5nWSJRbbkeXZtsMoMtrINPVrmY',
    appId: '1:274244221752:ios:7af04994421a8f6e169fcd',
    messagingSenderId: '274244221752',
    projectId: 'rememberme-860f1',
    storageBucket: 'rememberme-860f1.firebasestorage.app',
    iosBundleId: 'com.example.rememberme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnikljJd3sJB3pyjdkR0zJ0Z1vvXoI_pA',
    appId: '1:274244221752:web:be00b1071b8c8e22169fcd',
    messagingSenderId: '274244221752',
    projectId: 'rememberme-860f1',
    authDomain: 'rememberme-860f1.firebaseapp.com',
    storageBucket: 'rememberme-860f1.firebasestorage.app',
    measurementId: 'G-BFKT28W23Q',
  );
}
